(library
 (name ppx_expect)
 (public_name ppx_expect)
 (kind ppx_rewriter)
 (libraries
  ppxlib
  ppx_expect_runtime
  ppx_inline_test_nobase
  ppx_inline_test_nobase.libname
  ppx_here.expander)
 (ppx_runtime_libraries ppx_expect.runtime ppx_expect.config)
 (preprocess
  (pps ppxlib.metaquot))
 (inline_tests.backend
  (runner_libraries ppx_expect.evaluator)
  (extends ppx_inline_test_nobase)))
